blueprint:
  name: Aqara TRV – External Sensor (Auto-Fallback + Offset + Tolerance)
  description: >
    Controls an Aqara TRV using an external temperature sensor for stable room heating.
    Features:
      • Instant fallback to internal TRV sensor if external one is unavailable
      • Radiator heat compensation (turns off 0.3 °C early)
      • 0.4 °C tolerance to reduce toggling
      • No external Python script needed
      • Uses a number field for comfort temperature (10–30 °C)

  domain: automation
  input:
    trv_entity:
      name: Aqara TRV
      description: Select your TRV climate entity
      selector:
        entity:
          domain: climate

    external_temp_sensor:
      name: External temperature sensor
      description: Select the Aqara temperature sensor for this TRV
      selector:
        entity:
          domain: sensor
          device_class: temperature

    last_temp_helper:
      name: Helper for last external temperature
      description: Select or create an input_number helper to store last external temperature
      selector:
        entity:
          domain: input_number

    comfort_temperature:
      name: Comfort temperature
      description: Desired room temperature for comfort mode
      default: 22
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

variables:
  trv_entity: !input trv_entity
  external_temp_sensor: !input external_temp_sensor
  last_temp_helper: !input last_temp_helper
  comfort_temperature: !input comfort_temperature
  tolerance: 0.4
  radiator_offset: 0.3

trigger:
  # Trigger when external temperature changes
  - platform: state
    entity_id: !input external_temp_sensor

  # Trigger if external sensor becomes unavailable
  - platform: state
    entity_id: !input external_temp_sensor
    to:
      - "unavailable"
      - "unknown"
      - "undefined"

  # Trigger on HA startup and when automations reload
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

condition: [ ]

action:
  - variables:
      external_temp: "{{ states(external_temp_sensor) | float(0) }}"
      trv_temp: "{{ state_attr(trv_entity, 'current_temperature') | float(0) }}"
      last_external_temp: "{{ states(last_temp_helper) | float(0) }}"
      sensor_state: "{{ states(external_temp_sensor) }}"

  # Instant fallback to internal TRV temperature
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ sensor_state in ['unavailable', 'unknown', 'undefined'] }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: "{{ trv_entity }}"
            data:
              temperature: "{{ comfort_temperature }}"
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ trv_entity }}"
            data:
              hvac_mode: "heat"
          - stop: "External sensor unavailable – switched to internal TRV temperature"

  # Skip if external temperature change < tolerance
  - condition: template
    value_template: >
      {{ (external_temp - last_external_temp) | abs >= tolerance }}

  # Update stored last external temperature
  - service: input_number.set_value
    target:
      entity_id: "{{ last_temp_helper }}"
    data:
      value: "{{ external_temp }}"

  # Main heating control logic
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ external_temp < (comfort_temperature - radiator_offset) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ trv_entity }}"
            data:
              hvac_mode: "heat"
          - service: climate.set_temperature
            target:
              entity_id: "{{ trv_entity }}"
            data:
              temperature: "{{ comfort_temperature }}"
      - conditions:
          - condition: template
            value_template: >
              {{ external_temp >= (comfort_temperature - radiator_offset) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ trv_entity }}"
            data:
              hvac_mode: "off"

mode: restart
