blueprint:
  name: Aqara TRV – External Sensor (Comfort Mode, Auto-Fallback)
  description: >
    Controls an Aqara TRV using an external temperature sensor for comfort heating.
    - Uses external temperature sensor for control.
    - Falls back to TRV internal sensor if external becomes unavailable.
    - Turns off heating slightly before reaching comfort temperature (offset).
    - Sends updated measured temperature to TRV when target is reached.
    - Comfort temperature entered as a number between 10 °C and 30 °C.
    - Automation runs in restart mode to always act on latest readings.

  domain: automation
  input:
    trv_entity:
      name: Aqara TRV
      description: Select your TRV climate entity
      selector:
        entity:
          domain: climate

    external_temp_sensor:
      name: External temperature sensor
      description: Select your external room temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    last_temp_helper:
      name: Helper for last external temperature
      description: Select an input_number helper to store the last valid external temperature reading
      selector:
        entity:
          domain: input_number

    comfort_temperature:
      name: Comfort temperature
      description: Desired comfort temperature between 10 and 30 °C
      default: 22
      text:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

variables:
  trv_entity: !input trv_entity
  external_temp_sensor: !input external_temp_sensor
  last_temp_helper: !input last_temp_helper
  comfort_temperature: !input comfort_temperature
  tolerance: 0.4
  radiator_offset: 0.3

trigger:
  - platform: state
    entity_id: !input external_temp_sensor
  - platform: state
    entity_id: !input external_temp_sensor
    to:
      - "unavailable"
      - "unknown"
      - "undefined"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

condition: [ ]

action:
  - variables:
      sensor_state_raw: "{{ states(external_temp_sensor) }}"
      external_temp_value: >
        {% if sensor_state_raw in ['unavailable','unknown','undefined',None,'none','None'] %}
          none
        {% else %}
          {{ states(external_temp_sensor) | float }}
        {% endif %}
      last_external_temp_value: "{{ states(last_temp_helper) | float(0) }}"
      trv_internal_temp: "{{ state_attr(trv_entity, 'current_temperature') | float(0) }}"

  # Fallback: external sensor unavailable → use TRV internal reading
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ sensor_state_raw in ['unavailable','unknown','undefined',None,'none','None'] }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: "{{ trv_entity }}"
            data:
              temperature: "{{ comfort_temperature }}"
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ trv_entity }}"
            data:
              hvac_mode: "heat"
          - service: input_number.set_value
            target:
              entity_id: "{{ last_temp_helper }}"
            data:
              value: "{{ trv_internal_temp }}"
          - stop: "External sensor unavailable — fallback to internal TRV temperature."

  - variables:
      external_temp: "{{ external_temp_value | float }}"

  # Ignore small changes
  - condition: template
    value_template: >
      {{ (external_temp - last_external_temp_value) | abs >= tolerance }}

  # Update stored last temperature
  - service: input_number.set_value
    target:
      entity_id: "{{ last_temp_helper }}"
    data:
      value: "{{ external_temp }}"

  # Main heating control
  - choose:
      # Heating ON: external temp below comfort - offset
      - conditions:
          - condition: template
            value_template: >
              {{ external_temp < (comfort_temperature - radiator_offset) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ trv_entity }}"
            data:
              hvac_mode: "heat"
          - service: climate.set_temperature
            target:
              entity_id: "{{ trv_entity }}"
            data:
              temperature: "{{ comfort_temperature }}"
      # Heating OFF: temperature reached or exceeded
      - conditions:
          - condition: template
            value_template: >
              {{ external_temp >= (comfort_temperature - radiator_offset) }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: "{{ trv_entity }}"
            data:
              temperature: "{{ external_temp }}"
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ trv_entity }}"
            data:
              hvac_mode: "off"

mode: restart
