blueprint:
  name: Aqara TRV – External Sensor (Comfort/Eco with Schedule & Smart Heating)
  description: >
    Controls an Aqara TRV E1 using an external Aqara temperature sensor.
    Features:
      - Updates TRV internal temperature based on external sensor (same logic as pavax blueprint)
      - Automatic fallback to TRV internal sensor when external unavailable
      - Comfort/Eco temperature modes based on weekly schedules
      - Hysteresis heating logic (stop at target−0.2°C, start at target−0.5°C)
      - Uses TRV modes: heat/off only

  domain: automation

  input:
    aqara_trv:
      name: Aqara TRV
      description: The TRV climate entity to control.
      selector:
        entity:
          domain: climate

    aqara_trv_select_entity:
      name: TRV Sensor Mode Selector
      description: Select entity for TRV sensor source (internal/external).
      selector:
        entity:
          domain: select

    aqara_trv_number_entity:
      name: TRV External Temperature Number
      description: Number entity used to update TRV's internal value with external reading.
      selector:
        entity:
          domain: number

    external_sensor:
      name: External Temperature Sensor
      description: Aqara temperature & humidity sensor used for external reading.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    comfort_temperature:
      name: Comfort Temperature
      description: Desired temperature during comfort periods (15–30°C, decimals allowed).
      selector:
        number:
          min: 15
          max: 30
          step: 0.5
          mode: box

    eco_temperature:
      name: Eco Temperature
      description: Desired temperature during eco periods (15–30°C, decimals allowed).
      selector:
        number:
          min: 15
          max: 30
          step: 0.5
          mode: box

    schedules:
      name: Weekly Schedule
      description: >
        Define time-based mode switches between Comfort and Eco.
        Example:
          - days: [mon,tue,wed,thu,fri]
            start: "07:00"
            end: "09:00"
            mode: "comfort"
          - days: [mon,tue,wed,thu,fri]
            start: "22:00"
            end: "07:00"
            mode: "eco"
      selector:
        object:

trigger:
  - platform: state
    entity_id: !input external_sensor

mode: restart
max_exceeded: silent

variables:
  aqara_trv: !input aqara_trv
  aqara_trv_select_entity: !input aqara_trv_select_entity
  aqara_trv_number_entity: !input aqara_trv_number_entity
  external_sensor: !input external_sensor
  comfort_temperature: !input comfort_temperature
  eco_temperature: !input eco_temperature
  schedules: !input schedules

  now_time: "{{ now().strftime('%H:%M') }}"
  today: "{{ now().strftime('%a') | lower }}"

  external_temp: >
    {% set val = states(external_sensor) %}
    {% if val not in ['unavailable','unknown','undefined','none',''] %}
      {{ val | float }}
    {% else %}
      none
    {% endif %}

  active_mode: >
    {% set current_mode = 'eco' %}
    {% if schedules is defined and schedules %}
      {% for s in schedules %}
        {% set days = s.days if s.days is defined else [] %}
        {% set start = s.start if s.start is defined else '00:00' %}
        {% set end = s.end if s.end is defined else '23:59' %}
        {% set mode = s.mode if s.mode is defined else 'eco' %}

        {% set is_today = (today in days or 'all' in days) %}
        {% set crosses_midnight = (start > end) %}
        {% if is_today %}
          {% if (not crosses_midnight and start <= now_time < end)
             or (crosses_midnight and (now_time >= start or now_time < end)) %}
            {% set current_mode = mode %}
            {% break %}
          {% endif %}
        {% endif %}
      {% endfor %}
    {% endif %}
    {{ current_mode }}

  target_temp: >
    {% if active_mode == 'comfort' %}
      {{ comfort_temperature | float }}
    {% else %}
      {{ eco_temperature | float }}
    {% endif %}

condition: [ ]

action:
  # --- Handle unavailable or invalid external sensor (switch TRV to internal) ---
  - choose:
      - conditions: >
          {{ external_temp == 'none' or not (external_temp is number) }}
        sequence:
          - service: select.select_option
            target:
              entity_id: !input aqara_trv_select_entity
            data:
              option: internal
          - service: system_log.write
            data:
              level: error
              message: "External temperature sensor unavailable - switching TRV to internal sensor"
              logger: Aqara TRV
          - stop: External temperature sensor unavailable

  # --- External sensor available (switch TRV to external and update internal value) ---
  - service: select.select_option
    target:
      entity_id: !input aqara_trv_select_entity
    data:
      option: external

  - service: number.set_value
    target:
      entity_id: !input aqara_trv_number_entity
    data:
      value: "{{ external_temp | float }}"

  # --- Determine if we need to heat or turn off based on hysteresis ---
  - choose:
      # Stop heating if measured >= target - 0.2
      - conditions:
          - condition: template
            value_template: >
              {{ external_temp is number and external_temp >= (target_temp - 0.2) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ aqara_trv }}"
            data:
              hvac_mode: "off"

      # Start heating if measured <= target - 0.5
      - conditions:
          - condition: template
            value_template: >
              {{ external_temp is number and external_temp <= (target_temp - 0.5) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ aqara_trv }}"
            data:
              hvac_mode: "heat"
          - service: climate.set_temperature
            target:
              entity_id: "{{ aqara_trv }}"
            data:
              temperature: "{{ target_temp | float }}"

  # If neither condition matched, do nothing (temperature stable zone)
  - stop: Stable temperature zone — no action required.
