blueprint:
  name: Aqara TRV – External Sensor (Compact Comfort & Eco Schedule)
  description: >
    Controls an Aqara TRV using an external temperature sensor with comfort and eco modes,
    based on a compact schedule list similar to Advanced Heating Control.

    🧩 Features:
    - External sensor temperature control
    - Internal TRV fallback when sensor unavailable
    - Radiator heat compensation (offset)
    - Fractional temperatures supported (e.g., 23.3 °C)
    - Restart mode for fast response
    - Compact schedule UI (time, days, mode)
    - 5-minute recheck pattern

  domain: automation

  input:
    trv_entity:
      name: Aqara TRV
      selector:
        entity:
          domain: climate

    external_temp_sensor:
      name: External temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    last_temp_helper:
      name: Helper for last external temperature
      selector:
        entity:
          domain: input_number

    comfort_temperature:
      name: Comfort temperature
      description: Enter a decimal temperature between 10 and 30 °C
      default: "22.0"
      selector:
        text:
          type: number

    eco_temperature:
      name: Eco temperature
      description: Enter a decimal temperature between 10 and 30 °C
      default: "20.0"
      selector:
        text:
          type: number

    schedule_list:
      name: Heating schedule
      description: >
        Define your comfort and eco periods here.
        Each entry includes days, start and end times, and the mode to apply.
        Example values are provided — edit or add more as needed.
      default:
        - days: [ "mon", "tue", "wed", "thu", "fri" ]
          start: "06:30"
          end: "08:30"
          mode: "comfort"
        - days: [ "mon", "tue", "wed", "thu", "fri" ]
          start: "08:30"
          end: "16:00"
          mode: "eco"
        - days: [ "mon", "tue", "wed", "thu", "fri" ]
          start: "16:00"
          end: "23:00"
          mode: "comfort"
        - days: [ "sat", "sun" ]
          start: "07:00"
          end: "23:00"
          mode: "comfort"
      selector:
        object: { }

# ---------------- VARIABLES -----------------

variables:
  trv_entity: !input trv_entity
  external_temp_sensor: !input external_temp_sensor
  last_temp_helper: !input last_temp_helper
  comfort_temperature: !input comfort_temperature
  eco_temperature: !input eco_temperature
  schedule_list: !input schedule_list

  tolerance: 0.4
  radiator_offset: 0.3

trigger:
  - platform: state
    entity_id: !input external_temp_sensor
  - platform: state
    entity_id: !input external_temp_sensor
    to:
      - "unavailable"
      - "unknown"
      - "undefined"
  - platform: time_pattern
    minutes: "/5"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

condition: [ ]

# ---------------- ACTIONS -----------------

action:
  - variables:
      sensor_state_raw: "{{ states(external_temp_sensor) }}"
      last_external: "{{ states(last_temp_helper) | float(0) }}"
      trv_internal_temp: "{{ state_attr(trv_entity, 'current_temperature') | float(0) }}"
      comfort_temp_value: "{{ comfort_temperature | float }}"
      eco_temp_value: "{{ eco_temperature | float }}"
      current_day: "{{ now().strftime('%a') | lower }}"
      now_time: "{{ now().strftime('%H:%M') }}"

      # Determine which schedule is active (robust to midnight-crossing and "6:30" vs "06:30")
      active_mode: >
        {% set mode = 'comfort' %}
        {% for item in schedule_list %}
          {% set days = item.days if item.days is defined else [] %}
          {% if current_day in days %}
            {# normalize start/end to HH:MM with leading zero if needed #}
            {% set s_raw = item.start if item.start is defined else '' %}
            {% set e_raw = item.end if item.end is defined else '' %}
            {% if s_raw is string and s_raw|length == 4 %}{% set s = '0' + s_raw %}{% else %}{% set s = s_raw %}{% endif %}
            {% if e_raw is string and e_raw|length == 4 %}{% set e = '0' + e_raw %}{% else %}{% set e = e_raw %}{% endif %}
            {% if s and e %}
              {% if s <= e %}
                {% if s <= now_time < e and item.mode in ['comfort','eco'] %}
                  {% set mode = item.mode %}
                {% endif %}
              {% else %}
                {# crosses midnight: active if now >= s OR now < e #}
                {% if (now_time >= s or now_time < e) and item.mode in ['comfort','eco'] %}
                  {% set mode = item.mode %}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ mode }}

      active_temp: >
        {% if active_mode == 'eco' %}
          {{ eco_temp_value }}
        {% else %}
          {{ comfort_temp_value }}
        {% endif %}

  - condition: template
    value_template: "{{ 10 <= active_temp <= 30 }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ sensor_state_raw in ['unavailable','unknown','undefined'] }}"
        sequence:
          - service: climate.set_temperature
            target: { entity_id: "{{ trv_entity }}" }
            data: { temperature: "{{ active_temp }}" }

          - service: climate.set_hvac_mode
            target: { entity_id: "{{ trv_entity }}" }
            data: { hvac_mode: "heat" }

          - service: input_number.set_value
            target: { entity_id: "{{ last_temp_helper }}" }
            data: { value: "{{ trv_internal_temp }}" }

          - stop: "External sensor unavailable — fallback to TRV internal temperature."

  - variables:
      external_temp: "{{ states(external_temp_sensor) | float }}"

  - condition: template
    value_template: "{{ (external_temp - last_external) | abs >= tolerance }}"

  - service: input_number.set_value
    target: { entity_id: "{{ last_temp_helper }}" }
    data: { value: "{{ external_temp }}" }

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ external_temp < (active_temp - radiator_offset) }}"
        sequence:
          - service: climate.set_hvac_mode
            target: { entity_id: "{{ trv_entity }}" }
            data: { hvac_mode: "heat" }

          - service: climate.set_temperature
            target: { entity_id: "{{ trv_entity }}" }
            data: { temperature: "{{ active_temp }}" }

      - conditions:
          - condition: template
            value_template: "{{ external_temp >= (active_temp - radiator_offset) }}"
        sequence:
          - service: climate.set_temperature
            target: { entity_id: "{{ trv_entity }}" }
            data: { temperature: "{{ external_temp }}" }

          - service: climate.set_hvac_mode
            target: { entity_id: "{{ trv_entity }}" }
            data: { hvac_mode: "off" }

mode: restart
